In [13]:
from IPython.display import Image
from sklearn.cluster import KMeans
import numpy as np
import cv2

In [14]:
import numpy as np
import cv2
import os 
import csv
import colorsys
from sklearn.cluster import KMeans

# 데이터 폴더에서 이미지 파일이름 가져오기
file_list=os.listdir("C:/Users/Hong Sumin/Desktop/3-1/data/CHANEL5")
final_list=[]
column=["name","r","g","b","h","s","v"]

# 파일
for file in file_list:
    file_name=file.split(".")
    # 파일이름 가져오기
    file_name=file_name[0]
    file_name=file_name.split(" ")[0]
    print(file_name)
    img=cv2.imread("C:/Users/Hong Sumin/Desktop/3-1/data/CHANEL5/"+file)
    # rgb추출
    img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    # reshape
    img=img.reshape(img.shape[0]*img.shape[1],3)

    k=10
    # KMeans Clustering
    clt=KMeans(n_clusters=k)
    clt.fit(img)
    
    # center값
    for center in clt.cluster_centers_:
        print(center)
        hsv=colorsys.rgb_to_hsv(center[0],center[1],center[2])
        temp=[]
        # 파일이름 저장
        temp.append(file_name)
        # 센터값 저장
        for i in range(len(center)):
            temp.append(center[i])
        for i in range(len(hsv)):
            temp.append(hsv[i])
        # 최종 리스트에 저장    
        final_list.append(temp)
# csv 파일 저장 - 한글 깨지면 인코딩 바꿔야 할 수도…
file=open("CHANEL5.csv","w",newline='',)
csvfile=csv.writer(file)
for row in final_list:
    csvfile.writerow(row)
file.close()

CHANEL_ENDLESS1
[202.91611925  85.0085902   87.5755432 ]
[220.38828425 109.3028169  108.56914213]
[181.90866035  63.88294993  68.99864682]
[214.00134228  98.73557047  99.09798658]
[196.03536648  77.76678626  81.46591492]
[222.76603543 115.73915699 114.97617593]
[217.80629275 104.2746922  103.84377565]
[209.09752617  92.21788773  93.53425309]
[189.15088927  70.99368904  75.6087206 ]
[172.44285714  55.17777778  60.26349206]
CHANEL_ENDLESS10
[181.48187919  59.05234899  54.19261745]
[172.00925147  54.45668629  51.02691337]
[203.23706897  74.63793103  71.61637931]
[196.76003086  66.88734568  64.49228395]
[183.60483871  85.70967742  80.86290323]
[150.10044643  40.015625    37.82589286]
[172.81818182  63.87175325  59.42045455]
[189.68031088  62.2253886   57.49274611]
[163.00359281  47.53293413  45.49341317]
[185.14845938  73.08823529  68.29411765]
CHANEL_ENDLESS2
[198.1315623   65.4498735   64.50237192]
[207.71524288  92.39028476  91.662838  ]
[203.62141864  74.39833102  72.09568846]
[178.372

In [19]:
import cv2 
import numpy as np

def tracking(img_name): # img_name = 추출할 이미지 경로 혹은 이름
    img = cv2.imread(img_name) 
    lower_ba = np.array([204, 153, 153]) 
    upper_ba = np.array([255, 204, 204])
  #  ba_range=cv2.inRange(hsv,lower_ba,upper_ba)
    #for i in range(lower_red,upper_red):
    
    #153 102 g
    
   # while True:
        #ret, fram = img.read()
    hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
    
    
    red_range = cv2.inRange(hsv,lower_ba,upper_ba)
        
    red_result = cv2.bitwise_and(img,img,mask = red_range)
    red_result = cv2.resize(red_result,(300,300))
       
    img = cv2.resize(img,(300,300))
    
    # 원래 이미지 화면 띄우기
    cv2.imshow("original",img)
    # 추출한 이미지 화면 띄우기
    cv2.imshow("red",red_result)
    
    #추출한 이미지 저장
    cv2.imwrite('result1.PNG', red_result)
        
    cv2.waitKey(0)
        
    cv2.destroyAllWindows()
img_name = "C:/Users/Hong Sumin/Desktop/3-1/hi3.jpg"
tracking(img_name)

print(type(tracking(img_name)))
        

<class 'NoneType'>
